from aminor.models import Extension

e = Extension(nom_molecule='5FJC_A_138_1', libelle_PDB='SAM-I riboswitch bearing the H. marismortui Kt-7 variant C-2bU', type_molecule='Riboswitch', organisme='Caldanaerobacter subterraneurs subsp. Tengcongensis', num_PDB='5FJC', num_ch='A', num_motif='138', num_occ='1', url_PDB='https://www.rcsb.org/structure/5fjc')
e.save()
e = Extension(nom_molecule='5DM6_X_48_9', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='48', num_occ='9', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='1FJG_A_271_1', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='271', num_occ='1', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5J5B_BA_48_14', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='48', num_occ='14', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='4V9F_0_62_12', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='62', num_occ='12', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='3JCS_1_25_16', libelle_PDB='2.8 Angstrom cryo-EM structure of the large ribosomal subunit from the eukaryotic parasite Leishmania', type_molecule='ARNr 26S alpha', organisme='Leishmania donovani', num_PDB='3JCS', num_ch='1', num_motif='25', num_occ='16', url_PDB='https://www.rcsb.org/structure/3jcs')
e.save()
e = Extension(nom_molecule='5FDU_1A_137_6', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='137', num_occ='6', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='1GID_B_25_20', libelle_PDB='CRYSTAL STRUCTURE OF A GROUP I RIBOZYME DOMAIN: PRINCIPLES OF RNA PACKING', type_molecule='Ribozyme (domaine P4,P6)', organisme='synthétique', num_PDB='1GID', num_ch='B', num_motif='25', num_occ='20', url_PDB='https://www.rcsb.org/structure/1gid')
e.save()
e = Extension(nom_molecule='5FDU_1A_272_1', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='272', num_occ='1', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='5J7L_DA_30_15', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='30', num_occ='15', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='1FJG_A_48_11', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='48', num_occ='11', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5DM6_X_48_10', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='48', num_occ='10', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='4V9F_0_30_23', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='30', num_occ='23', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5J7L_DA_25_10', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='25', num_occ='10', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='5FDU_1A_134_3', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='134', num_occ='3', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='5J7L_DA_272_2', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='272', num_occ='2', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_30_4', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='30', num_occ='4', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='4V88_A6_48_12', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 18S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A6', num_motif='48', num_occ='12', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='5J7L_DA_197_4', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='197', num_occ='4', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_48_13', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='48', num_occ='13', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='3UCZ_R_62_15', libelle_PDB='The c-di-GMP-I riboswitch bound to GpG', type_molecule='Riboswitch', organisme='Homo sapiens', num_PDB='3UCZ', num_ch='R', num_motif='62', num_occ='15', url_PDB='https://www.rcsb.org/structure/3ucz')
e.save()
e = Extension(nom_molecule='4V9F_0_207_3', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='207', num_occ='3', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='3JCS_1_48_18', libelle_PDB='2.8 Angstrom cryo-EM structure of the large ribosomal subunit from the eukaryotic parasite Leishmania', type_molecule='ARNr 26S alpha', organisme='Leishmania donovani', num_PDB='3JCS', num_ch='1', num_motif='48', num_occ='18', url_PDB='https://www.rcsb.org/structure/3jcs')
e.save()
e = Extension(nom_molecule='4PRF_B_25_69', libelle_PDB='A Second Look at the HDV Ribozyme Structure and Dynamics', type_molecule='Ribozyme', organisme='Hepatitis Delta virus', num_PDB='4PRF', num_ch='B', num_motif='25', num_occ='69', url_PDB='https://www.rcsb.org/structure/4prf')
e.save()
e = Extension(nom_molecule='5FDU_1A_62_14', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='62', num_occ='14', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='4YAZ_R_36_25', libelle_PDB='3',3'-cGAMP riboswitch bound with 3',3'-cGAMP', type_molecule='Riboswitch', organisme='Geobacter', num_PDB='4YAZ', num_ch='R', num_motif='36', num_occ='25', url_PDB='https://www.rcsb.org/structure/4yaz')
e.save()
e = Extension(nom_molecule='5DM6_X_134_2', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='134', num_occ='2', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5DM6_X_227_2', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='227', num_occ='2', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5FDU_1A_25_78', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='25', num_occ='78', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='4V9F_0_48_26', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='48', num_occ='26', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='1FJG_A_48_17', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='48', num_occ='17', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5FDU_1A_25_68', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='25', num_occ='68', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='5FDU_1A_48_25', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='48', num_occ='25', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='1FJG_A_48_8', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='48', num_occ='8', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5J5B_BA_138_2', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='138', num_occ='2', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='5J7L_DA_30_36', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='30', num_occ='36', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V88_A5_48_3', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='48', num_occ='3', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='4V9F_0_25_4', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='25', num_occ='4', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5FDU_1A_197_3', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='197', num_occ='3', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='4V88_A5_287_1', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='287', num_occ='1', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='3JCS_1_282_1', libelle_PDB='2.8 Angstrom cryo-EM structure of the large ribosomal subunit from the eukaryotic parasite Leishmania', type_molecule='ARNr 26S alpha', organisme='Leishmania donovani', num_PDB='3JCS', num_ch='1', num_motif='282', num_occ='1', url_PDB='https://www.rcsb.org/structure/3jcs')
e.save()
e = Extension(nom_molecule='3JCS_2_30_56', libelle_PDB='2.8 Angstrom cryo-EM structure of the large ribosomal subunit from the eukaryotic parasite Leishmania', type_molecule='ARNr 26S delta', organisme='Leishmania donovani', num_PDB='3JCS', num_ch='2', num_motif='30', num_occ='56', url_PDB='https://www.rcsb.org/structure/3jcs')
e.save()
e = Extension(nom_molecule='5J7L_DA_170_5', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='170', num_occ='5', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_44_3', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='44', num_occ='3', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='4V88_A5_25_30', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='25', num_occ='30', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='5J7L_DA_134_1', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='134', num_occ='1', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='1U9S_A_25_74', libelle_PDB='Crystal structure of the specificity domain of Ribonuclease P of the A-type', type_molecule='Ribonucléase P', organisme='Inconnu', num_PDB='1U9S', num_ch='A', num_motif='25', num_occ='74', url_PDB='https://www.rcsb.org/structure/1u9s')
e.save()
e = Extension(nom_molecule='5J7L_DA_48_15', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='48', num_occ='15', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='5DM6_X_127_7', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='127', num_occ='7', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5J5B_BA_48_23', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='48', num_occ='23', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='1FJG_A_294_1', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='294', num_occ='1', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5J7L_DA_62_5', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='62', num_occ='5', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='5J5B_BA_294_2', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='294', num_occ='2', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='4V9F_0_48_2', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='48', num_occ='2', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='4V9F_0_48_16', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='48', num_occ='16', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5J7L_DA_50_21', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='50', num_occ='21', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='5FDU_1A_48_19', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='48', num_occ='19', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='5J7L_DA_48_20', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='48', num_occ='20', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_25_56', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='25', num_occ='56', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5DM6_X_25_15', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='25', num_occ='15', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5J7L_DA_36_3', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='36', num_occ='3', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='5J5B_BA_48_5', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='48', num_occ='5', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='4V9F_0_137_5', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='137', num_occ='5', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5J7L_DA_48_30', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='48', num_occ='30', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_134_5', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='134', num_occ='5', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='1FJG_A_138_3', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='138', num_occ='3', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='4V88_A5_25_47', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='25', num_occ='47', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='2XD0_V_36_21', libelle_PDB='A processed non-coding RNA regulates a bacterial antiviral system', type_molecule='ARN non codant (toxine)', organisme='Pectobacterium atrosepticum', num_PDB='2XD0', num_ch='V', num_motif='36', num_occ='21', url_PDB='https://www.rcsb.org/structure/2xd0')
e.save()
e = Extension(nom_molecule='5J5B_BA_48_7', libelle_PDB='Structure of the WT E coli ribosome bound to tetracycline', type_molecule='ARNr 16S', organisme='Escherichia coli', num_PDB='5J5B', num_ch='BA', num_motif='48', num_occ='7', url_PDB='https://www.rcsb.org/structure/5j5b')
e.save()
e = Extension(nom_molecule='4V88_A5_48_6', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='48', num_occ='6', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='5DM6_X_25_34', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='25', num_occ='34', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5DM6_X_328_2', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='328', num_occ='2', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='5FDU_1A_290_2', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='290', num_occ='2', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='5J7L_DA_48_1', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='48', num_occ='1', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4V9F_0_48_21', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='48', num_occ='21', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='5J7L_DA_25_12', libelle_PDB='Structure of the 70S E coli ribosome with the U1052G mutation in the 16S rRNA bound to tetracycline', type_molecule='ARNr 23S', organisme='Escherichia coli', num_PDB='5J7L', num_ch='DA', num_motif='25', num_occ='12', url_PDB='https://www.rcsb.org/structure/5j7l')
e.save()
e = Extension(nom_molecule='4FAU_A_207_4', libelle_PDB='Structure of Oceanobacillus iheyensis group II intron in the presence of Li+, Mg2+ and 5'-exon', type_molecule='Intron', organisme='Oceanobacillus iheyensis', num_PDB='4FAU', num_ch='A', num_motif='207', num_occ='4', url_PDB='https://www.rcsb.org/structure/4fau')
e.save()
e = Extension(nom_molecule='1FJG_A_109_6', libelle_PDB='STRUCTURE OF THE THERMUS THERMOPHILUS 30S RIBOSOMAL SUBUNIT IN COMPLEX WITH THE ANTIBIOTICS STREPTOMYCIN, SPECTINOMYCIN, AND PAROMOMYCIN', type_molecule='ARNr 16S', organisme='Thermus  thermophilus', num_PDB='1FJG', num_ch='A', num_motif='109', num_occ='6', url_PDB='https://www.rcsb.org/structure/1fjg')
e.save()
e = Extension(nom_molecule='5FDU_1A_74_7', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='74', num_occ='7', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='4V88_A5_30_5', libelle_PDB='The structure of the eukaryotic ribosome at 3.0 A resolution', type_molecule='ARNr 25S', organisme='Saccharomyces cerevisiae', num_PDB='4V88', num_ch='A5', num_motif='30', num_occ='5', url_PDB='https://www.rcsb.org/structure/4v88')
e.save()
e = Extension(nom_molecule='3JCS_1_25_46', libelle_PDB='2.8 Angstrom cryo-EM structure of the large ribosomal subunit from the eukaryotic parasite Leishmania', type_molecule='ARNr 26S alpha', organisme='Leishmania donovani', num_PDB='3JCS', num_ch='1', num_motif='25', num_occ='46', url_PDB='https://www.rcsb.org/structure/3jcs')
e.save()
e = Extension(nom_molecule='5DM6_X_48_28', libelle_PDB='Crystal structure of the 50S ribosomal subunit from Deinococcus radiodurans', type_molecule='ARNr 23S', organisme='Deinococcus radiodurans', num_PDB='5DM6', num_ch='X', num_motif='48', num_occ='28', url_PDB='https://www.rcsb.org/structure/5dm6')
e.save()
e = Extension(nom_molecule='1U9S_A_58_11', libelle_PDB='Crystal structure of the specificity domain of Ribonuclease P of the A-type', type_molecule='Ribonucléase P', organisme='Inconnu', num_PDB='1U9S', num_ch='A', num_motif='58', num_occ='11', url_PDB='https://www.rcsb.org/structure/1u9s')
e.save()
e = Extension(nom_molecule='5FDU_1A_30_17', libelle_PDB='Crystal structure of the Metalnikowin I antimicrobial peptide bound to the Thermus thermophilus 70S ribosome', type_molecule='ARNr 23S', organisme='Thermus thermophilus', num_PDB='5FDU', num_ch='1A', num_motif='30', num_occ='17', url_PDB='https://www.rcsb.org/structure/5fdu')
e.save()
e = Extension(nom_molecule='4V9F_0_127_6', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='127', num_occ='6', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
e = Extension(nom_molecule='4L81_A_25_77', libelle_PDB='Structure of the SAM-I/IV riboswitch (env87(deltaU92, deltaG93))', type_molecule='Riboswitch (aptamère, variant)', organisme='Inconnu', num_PDB='4L81', num_ch='A', num_motif='25', num_occ='77', url_PDB='https://www.rcsb.org/structure/4l81')
e.save()
e = Extension(nom_molecule='4V9F_0_287_2', libelle_PDB='The re-refined crystal structure of the Haloarcula marismortui large ribosomal subunit at 2.4 Angstrom resolution: more complete structure of the L7/L12 and L1 stalk, L5 and LX proteins', type_molecule='ARNr 23S', organisme='Haloarcula marismortui', num_PDB='4V9F', num_ch='0', num_motif='287', num_occ='2', url_PDB='https://www.rcsb.org/structure/4v9f')
e.save()
